### ISSUE TITLE
update cromwell in conda/conda-forge to latest version?

### ISSUE THREAD

**Issue by kapsakcj** [conda-forge/cromwell-feedstock#60]
### Comment:

Hi, I would like to be able to install cromwell via `conda`/`mamba` etc. and it appears that the latest available version is 83 (released July 2022) whereas the latest available cromwell release is 86 (released Oct 2023).

Would it be possible to make version 86 available via conda-forge?

Not sure if I'm in the right github repo or not. Please let me know if there's a better place to ask.

Thought I'd ask here before opening an issue over on the main cromwell repo: https://github.com/broadinstitute/cromwell/

I can attempt to submit a PR, but I have little experience with updating conda recipes & builds & such so I'm a little apprehensive.

**Comment by kapsakcj** [comment]
Oh... I'm just now seeing PR #59 ... my bad.

Is all that's needed is to merge the PR? Or is there code changes and/or testing required?

**Comment by notestaff** [comment]
@kapsakcj thanks for pointing out the lagging release -- am fixing that now.

**Comment by kapsakcj** [comment]
thank you so much!

**Comment by notestaff** [comment]
cromwell is now updated to 86 with #61 .

**Comment by kapsakcj** [comment]
that was lightning-fast. Thank you @notestaff !
